FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Enrolling_Service/models.py /app/Enrolling_Service/models.py
COPY Auth_Service/models.py /app/Auth_Service/models.py
COPY Management_Service/models.py /app/Management_Service/models.py
COPY database.py /app/database.py
COPY config.py /app/config.py
COPY alembic.ini /app/alembic.ini
COPY alembic /app/alembic


CMD ["alembic", "upgrade", "head"]