FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# COPY ./Enrolling_Service .
# COPY ./Enrolling_Service/main.py .
# COPY ./Management_Service/models.py /app/Management_Service/models.py
# COPY ./Auth_Service/models.py /app/Auth_Service/models.py
# COPY database.py .
COPY ./tests .

COPY config.py .

CMD ["pytest", "--maxfail=5", "--disable-warnings"]