"""Delete duration from course table

Revision ID: 519aa94b3286
Revises: 371191734d2d
Create Date: 2024-12-03 23:45:26.749643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519aa94b3286'
down_revision: Union[str, None] = '371191734d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'duration')
    op.drop_constraint('schedule_course_course_id_fkey', 'schedule_course', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_course', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_course', type_='foreignkey')
    op.create_foreign_key('schedule_course_course_id_fkey', 'schedule_course', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('course', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
