"""Revised migration

Revision ID: 55b59440a096
Revises: 5a8619441fde
Create Date: 2024-11-20 20:35:25.571501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55b59440a096'
down_revision: Union[str, None] = '5a8619441fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('schedule_course', sa.Column('start_date', sa.TIMESTAMP(), nullable=False))
    op.add_column('schedule_course', sa.Column('end_date', sa.TIMESTAMP(), nullable=False))
    op.drop_column('schedule_course', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_course', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('schedule_course', 'end_date')
    op.drop_column('schedule_course', 'start_date')
    op.drop_column('course', 'duration')
    # ### end Alembic commands ###
