FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./Telegram_Bot .
COPY config.py .
COPY ./Notification_Service/celery_app.py ./Notification_Service/celery_app.py

CMD ["python", "main.py"]