FROM python:3.12-slim

RUN adduser --disabled-password celeryuser

USER root

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY ./Telegram_Bot/ .
COPY config.py .
USER celeryuser

CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "-Q", "notifications"]
